### PR TITLE
Added new features

### PR DESCRIPTION
**Pull request by d1maxa**
-800x600 resolution support in single player mode
-Joystick support in single player mode
-4 joysticks support in multiplayer
-Joystick supports correctly 'power reverse option' now (like keyboard)
-5-12 planes support in multiplayer
-1200x400 and 2400x200 resolutions support (start game with '-1split' or '-nosplit' command line option)
-Fixed ai for Finland and England on Cavern map in multiplayer

### CODE REVIEW

**Comment by vranki** [comment]
Thanks very much, these changes look really cool!

A couple of changes if possible before merging:

* Add the -1split and -nosplit command line options to the help text that you get by running ./triplane --help
* Edit the readme.md so that it points to my git repo with all changes in one list. After merging the PR it's the new upstream.

I haven't tested the changes throughly but at least it still builds & starts fine.

**Comment by vranki** [comment]
Merged, thanks again for contributing. Can't wait to test the new features..

**Comment by d1maxa** [comment]
I made changes as you wished.
About testing: I finished all of 4 solo campaigns in 800x600 mode, it was very interesting :+1: 
Also played multiplayer with 12 planes, this was unstoppable action. In theory all of them can be controlled by human, we need to make control interface only.

**Comment by d1maxa** [comment]
I released binaries also: https://github.com/d1maxa/triplane/releases/tag/v1.0.8b (build for windows is not very trivial)

**Comment by vranki** [comment]
Looks like mxe (http://mxe.cc/) has good support for SDL so we could setup a script to cross-compile windows binaries. Travis can be used to create nightly builds from git.

**Pull request merged**
